;;; jetpacs-init.el --- Jetpacs foundation entry point -*- lexical-binding: t; -*-

;; JETPACS-MANAGED — loaded by the single seam line in your init.el:
;;
;;   (load (expand-file-name "jetpacs/jetpacs-init.el" user-emacs-directory) t)
;;
;; Do not edit this file: it self-updates from the newest staged copy, so
;; your changes would be lost.  Put personal overrides in
;; ~/.emacs.d/jetpacs/user.el (created once, loaded last, wins).  Install
;; apps by listing their bundle in ~/.emacs.d/jetpacs/apps.el.
;;
;; This file stays deliberately thin — it only makes lib/jetpacs-core.el
;; present and requires it; everything else is `jetpacs-config-bootstrap',
;; which lives in the versioned core bundle.

(defvar jetpacs-root (expand-file-name "jetpacs/" user-emacs-directory)
  "The Jetpacs-owned directory tree (defined again, as a defconst, by core).")
(defvar jetpacs-lib-dir (expand-file-name "lib/" jetpacs-root)
  "Where adopted single-file bundles live (defined again by core).")
(defconst jetpacs-init--staging '("/sdcard/Documents/" "/sdcard/Download/")
  "Staging dirs checked before core loads (core has its own copy after).")

(defun jetpacs-init--ensure-core ()
  "Make sure lib/jetpacs-core.el exists and is the newest available copy.
Adopt from staging when a newer copy is there; otherwise fall back to the
legacy ~/.emacs.d/elisp/jetpacs-core.el.  This is the ONLY bundle handled
inline — once core is required, `jetpacs-config-bootstrap' does the rest."
  (let ((installed (expand-file-name "jetpacs-core.el" jetpacs-lib-dir)))
    (make-directory jetpacs-lib-dir t)
    (let ((staged (seq-find
                   (lambda (s) (and (file-readable-p s)
                                    (or (not (file-exists-p installed))
                                        (file-newer-than-file-p s installed))))
                   (mapcar (lambda (d) (concat d "jetpacs-core.el"))
                           jetpacs-init--staging)))
          (legacy (expand-file-name "elisp/jetpacs-core.el" user-emacs-directory)))
      (cond (staged (copy-file staged installed t))
            ((and (not (file-exists-p installed)) (file-readable-p legacy))
             (copy-file legacy installed t))))))

;; Self-heal: if a newer copy of THIS file is staged, adopt it and re-load
;; from it, so a foundation update never needs a second paste into init.el.
(let* ((self (or load-file-name buffer-file-name))
       (newer (and self (seq-find
                         (lambda (s) (and (file-readable-p s)
                                          (file-newer-than-file-p s self)))
                         (mapcar (lambda (d) (concat d "jetpacs-init.el"))
                                 jetpacs-init--staging)))))
  (if newer
      (progn (copy-file newer self t)
             (load self nil 'nomessage))
    ;; Foundation: adopt + require core STRUCTURALLY (not via apps.el, so an
    ;; app-list edit can never disable the bridge), then hand off to core.
    (add-to-list 'load-path jetpacs-lib-dir)
    (jetpacs-init--ensure-core)
    (require 'jetpacs-core)
    (jetpacs-config-bootstrap)))

(provide 'jetpacs-init)
;;; jetpacs-init.el ends here
